# Regime-Adaptive Intraday Alpha Program  
### Dual-Architecture Quantitative Research Framework  
### Structural Hypothesis Testing, Parameter Governance & Institutional Validation

---

## 1. Research Objective

This project develops and evaluates two competing intraday alpha architectures operating on 5-minute bars:

- **Model A (Control): Price-Derivative Momentum Framework**
- **Model B (Experimental): Flow-Structural Microstructure Framework**

The objective is to determine whether:

> Traditional short-horizon price momentum (EMA-based structure aligned with VWAP)  
> OR  
> Flow-derived volume pressure signals combined with auction-theory structural filters  

exhibit more durable, regime-robust alpha under identical institutional validation controls.

The emphasis of this research is not performance maximization, but:

- Structural hypothesis validation  
- Parameter stability  
- Regime robustness  
- Cost-adjusted durability  
- Statistical credibility  

Model A serves as the **control architecture**.  
Model B serves as the **experimental upgrade**.

---

# PART I — MODEL A (CONTROL)
## Price-Derivative Momentum Framework

---

## 2. Structural Hypothesis — Model A

The core hypothesis is:

1. Persistent positioning relative to VWAP reflects intraday institutional directional bias.
2. Short-horizon EMA cross events represent momentum inflection points with decaying predictive value.
3. Volatility regimes materially affect signal reliability.
4. Structural alignment (VWAP + trend + momentum) reduces false positives.
5. Risk anchored to structural invalidation improves payoff convexity.
6. Intraday signal strength varies by time-of-day and must be statistically derived.

This defines the control signal family.

---

## 3. Structural (Non-Optimized) Definitions — Model A

The following define the modeling space and will **not** be statistically tuned:

- 5-minute bar resolution  
- EMA(9,20) as baseline short-horizon momentum pair  
- HMA(20) as structural trend filter  
- RSI(14) and default MACD parameters  
- Fixed notional position sizing  
- Initial capital baseline  

These define the hypothesis space.

---

## 4. Correlation-Defined Universe Construction — Model A

### 4.1 Anchor Asset

NVDA is designated as the anchor asset.

### 4.2 Universe Selection Methodology

For each candidate equity:

$ρ_i = Corr(r_i, r_NVDA)$

Where:

- $r_i$ = daily log returns of stock i  
- $r_NVDA$ = daily log returns of NVDA  
- Correlation window = 252 trading days  

Stocks are ranked by rolling correlation during a predefined universe formation period.

The top N correlated stocks form the trading universe.

The universe is frozen before the primary evaluation period to prevent look-ahead bias.

---

## 5. Statistically Governed Parameters (Applies to Model A)

The following variables will be empirically derived using controlled statistical analysis:

### Volatility Conditioning
- ATR lookback length
- ATR percentile threshold for participation

### Momentum Freshness
- EMA cross freshness window (maximum bar age)

### Structural Activation
- VWAP structural activation delay (bars after two-sided confirmation)
- VWAP proximity band at cross event

### Risk Management
- Initial stop-loss distance (VWAP-anchored)
- Breakeven trigger distance
- EMA/HMA structural reversal buffer

### Structural Trend Filters
- VWAP slope lookback window (longs)
- VWAP slope lookback window (shorts)

### Intraday Participation
- Statistically derived session windows based on time-of-day signal significance

Each parameter will be selected based on:

- Distributional analysis (MAE/MFE)
- Conditional forward return studies
- Stability plateaus across neighborhoods
- Regime robustness
- Cross-sectional consistency

No parameter will be selected solely on peak Sharpe.

---

## 6. Session Derivation Protocol — Model A

1. Identify all EMA cross events.
2. Compute forward returns at multiple horizons.
3. Group events by time-of-day buckets.
4. Compute:
   - Mean forward return
   - t-statistic
   - Cross-to-cross move distribution
5. Exclude time regimes where:
   - Forward returns are statistically insignificant, or
   - Cross-to-cross moves are economically negligible.

Session participation is data-driven.

---

# PART II — MODEL B (EXPERIMENTAL)
## Flow-Structural Microstructure Framework

---

## 7. Structural Hypothesis — Model B

Model B tests whether intraday alpha is better explained by:

1. Volume-weighted directional pressure rather than lagging price derivatives.
2. Auction-based structural acceptance (POC) rather than arbitrary smoothing filters.
3. Liquidity- and volatility-adaptive universe construction.
4. Institutional participation intensity via time-relative volume.
5. Explicit friction-aware execution modeling.

Model B challenges whether price momentum is the dominant short-horizon signal family.

---

## 8. Dynamic Universe Construction — Model B

### V1 Limitation
Correlation anchoring introduces:
- Idiosyncratic regime bias  
- Sector concentration drift  
- Structural macro dependence  

### V2 Implementation

Daily rebalanced universe using strictly lagged data:

1. Rank equities by 14-day ATR relative to price:
   ATR_Ratio_i = ATR_14_i / Price_i

2. Filter for:
   - Minimum average dollar liquidity
   - Above-average pre-market participation

3. Select Top 50 daily.

This ensures capital deployment where volatility and liquidity actually exist.

---

## 9. Signal Generation — Estimated Volume Delta (EVD)

Per-bar pressure proxy:

$EVD_t = V_t × ( 2 × (C_t - L_t) / (H_t - L_t) - 1 )$

Interpretation:

- Close near high → buyer dominance  
- Close near low → seller dominance  
- Volume-weighted aggressor pressure approximation  

To eliminate historical drag:

Flow_t = rolling sum of recent EVD  
or slope of EVD window.

Window length will be statistically derived and perturbation-tested.

---

## 10. Structural Trend Filter — Volume Profile & POC

Construct intraday volume profile using 1-minute or 5-minute data.

POC = price level with highest accepted traded volume during session.

Long condition requires:
- Price > VWAP
- Price > POC

Short condition requires:
- Price < VWAP
- Price < POC

POC resolution will be stability-tested across price bin sizes.

---

## 11. Institutional Participation Filter — Time-of-Day RVOL

Procedure:

1. Drop half-days and early closes.
2. Group bars by exact time-of-day.
3. Compute rolling median of last 20 valid same-time observations.

RVOL_t = V_t / Median(V_{t, last 20 valid same-time observations})

Require:
RVOL_t ≥ threshold (e.g., 2.0, perturbation-tested ± neighborhood).

This ensures structural activation only during institutional participation regimes.

---

# PART III — COMMON EXECUTION & VALIDATION

---

## 12. Execution Model (Shared)

- Signals computed at close of bar t.
- Entry executed at open of bar t+1.
- All exits triggered at close of bar t execute at open of bar t+1.
- No overnight exposure.
- One active position per asset.
- Multiple trades per day permitted.

PnL:

Long:
(Exit − Entry) × Qty

Short:
(Entry − Exit) × Qty

Performance evaluated separately:
- Long-only
- Short-only
- Combined

---

## 13. Transaction Cost Analysis (Applied to Both Models)

5 bps round-trip (2.5 bps per side).

Long Entry:
Actual_Entry = Theoretical_Open × (1 + 0.00025)

Long Exit:
Actual_Exit = Theoretical_Exit × (1 − 0.00025)

Equivalent mirrored logic for shorts.

Sensitivity analysis includes ±1–2 bps perturbation.

Alpha must survive cost-adjusted evaluation.

---

## 14. Time Governance & Validation Framework

Data Range: 2016–2026

### A. Static Parameter Validation

Calibration: 2016–2019  
Out-of-Sample: 2020–2026  

Parameters locked post-calibration.

---

### B. Rolling Recalibration Validation

Train 2016–2019 → Test 2020  
Train 2017–2020 → Test 2021  
Train 2018–2021 → Test 2022  
Train 2019–2022 → Test 2023  
Train 2020–2023 → Test 2024  
Train 2021–2024 → Test 2025  

2026 remains untouched as final holdout.

---

## 15. Structural Stability & Perturbation Analysis

Each model must pass:

- Parameter neighborhood testing
- Volatility segmentation
- Regime segmentation
- Long vs short decomposition
- Cross-sectional robustness
- Trade density stability
- Drawdown profile similarity

Stability criteria:

- Sharpe within acceptable band
- Trade count does not collapse
- Drawdown profile remains structurally consistent

No parameter selected solely on peak Sharpe.

---

## 16. Core Research Question

This program explicitly tests:

Does traditional short-horizon price momentum outperform flow-derived microstructure pressure signals under identical institutional validation constraints?

If Model B outperforms Model A across:

- Static OOS
- Rolling validation
- Cost-adjusted performance
- Perturbation stability
- Regime segmentation

Then flow pressure demonstrates structural superiority.

If Model A remains more robust, price momentum remains the dominant structural signal family.

Either outcome is a valid research result.

---

## 17. Research Classification

This project represents:

A dual-architecture intraday alpha research program comparing price-derivative momentum signals against flow-structural microstructure signals under disciplined statistical parameter governance, dynamic universe construction, realistic execution modeling, and bias-aware multi-regime validation protocols.

The objective is not to optimize a backtest.

The objective is to determine which structural signal family exhibits durable, statistically defensible alpha.

We start by importing all the libraries we will need in this project

In [1]:
import os
import sys
import warnings
from pathlib import Path
from datetime import datetime, timedelta

warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
import matplotlib.pyplot as plt
import scipy.stats as stats
import yaml
from dotenv import load_dotenv

from alpaca.data.historical import StockHistoricalDataClient
from alpaca.data.requests import StockBarsRequest
from alpaca.data.timeframe import TimeFrame

NOTEBOOK_ROOT = Path.cwd().parent
if str(NOTEBOOK_ROOT) not in sys.path:
    sys.path.insert(0, str(NOTEBOOK_ROOT))

from src.config.settings import (
    PROJECT_ROOT,
    settings,
    cfg,
    client,
    DATA_DIR,
    START_YEAR,
    END_YEAR,
    RAW_PATH,
    DERIVED_PATH,
    FEATURES_PATH,
    UNIVERSE_PATH,
    REPORTS_PATH,
    DATA_START,
    DATA_END,
    FEED,
    ADJUSTMENT,
    TIMEZONE,
)
from src.config.ticker_universe import TICKERS
from src.data_ingestion.fetch_bars import fetch_minute_bars
from src.data_ingestion.parquet_storage import save_to_parquet, load_parquet, parquet_exists
from src.data_ingestion.backfill_pipeline import run_backfill
from src.tests.system_check import run_system_check
from src.data_ingestion.run_ingestion import run_full_backfill

print("Libraries loaded successfully ✅")
print("Tickers:", TICKERS)
print("Raw path:", RAW_PATH)
print("Date range:", DATA_START, "to", DATA_END)

Libraries loaded successfully ✅
Tickers: ['NVDA', 'AAPL', 'GOOG', 'MSFT', 'AMZN', 'TSM', 'META', 'AVGO', 'TSLA', '005930.KS', 'TECHY', 'ASML', 'ORCL', '000660.KS', 'NFLX', 'MU', 'PLTR', 'AMD', 'BABA', 'CSCO', 'AMAT', 'LRCX', 'IBM', 'SAP', 'KLAC', 'TXN', 'SHOP', 'APP', 'ANET', 'SU.PA', 'UBER', 'ADI', 'BKNG', 'QCOM', 'PDD', 'PANW', 'INTU', 'NOW', 'SONY', 'ARM', '8035.T', 'ADBE', '6857.T', 'SPOT', 'XIACF', 'CRWD', '2308.TW', 'DELL', '2317.TW', '6861.T', 'EQIX', 'ADP', 'MELI', '2454.TW', 'SNPS', 'CDNS', 'ABNB', 'STX', 'MRVL', 'DASH', 'SDNK', '0981.HK', 'NTES', '688256.SS', 'HOOD', 'NET', '7974.T', 'FTNT', 'SNOW', 'TEL', '36990.HK', 'IFX.DE', 'ADSK', 'SE', 'COIN', 'NXPI', '6146.T', 'MPWR', 'UNH', 'HCA', 'MCK', 'CVS', 'CI', 'COR', 'ELV', 'SHL.DE', 'CAH', 'MDLN', 'FRE.DE', 'CNC', 'THC', 'Q0F.SI', '6618.HK', 'RDOR3.SA', 'OHI', '300015.SZ', 'FPH.NZ', 'FMS', 'ENSG', 'SOLV', 'GH', 'LLY', 'JNJ', 'ABBV', 'ROG.SW', 'NVS', 'AZN', 'MRK', 'AMGN', 'GILD', 'NVO', 'PFE', 'BMY', 'VRTX', 'GSK', 'SNY', 'REGN', 'TEK', 'ZTS', 'UCB.VI', '600276.SS', 'CSL.AX', 'GALD.SW', 'SUNPHARMA.NS', 'LONN.SW', 'ARGX', '2359.HK', 'JPM', 'V', 'MA', '1398.HK', 'BAC', '601939.SS', '601288.SS', 'HSBC', 'MS', 'WFC', '601988.SS', 'GS', 'RY', 'AXP', 'CBA.AX', 'MUFG', 'C', 'SCHW', 'SAN', 'TD', '3968.HK', 'HDB', 'SPGI', 'SMFG', 'D05.SI', 'UBS', 'BBVA', 'COF', 'SBIN.NS', 'CME', 'IBKR', 'BNP.PA', 'UCG.MI', '1120.SR', 'ISP.MI', 'IBN', 'NAB.AX', 'BMO', 'MFG', 'WBC.AX', 'ICE', 'CM', 'ITUB', 'BPAC3.SA', 'BNS', '601658.SS', '601328.SS', 'SBER.ME', 'MCO', 'WMT', 'COST', 'HD', 'ITX.MC', 'TJX', 'LOW', '9983.T', 'ROST', 'AZO', 'WES.AX', 'ATD.TO', 'WMMVF', 'TGT', 'L.TO', 'KR', 'AD.AS', 'JD', 'TSCO.L', 'DOL.TO', '8267.T', 'CPNG', 'DG', 'HM-B.ST', 'WOW.AX', 'GE', 'CAT', 'CYATY', 'RTX', 'GEV', 'SMAWF', 'SIEGY', 'BA', 'SBGSF', 'SBGSY', 'EADSY', 'EADSF', 'DE', 'HON', 'ABLZF', 'LMT', 'SAFRY', 'ABBNY', 'SAFRF', 'UNP', 'SMEGF', 'SMERY', 'RYCEY', 'RYCEF', 'HTHIF', 'ETN', 'HTHIY', 'PH', 'MSBHF', 'MTSUY', 'NOC', 'MITSF', 'MITSY', 'DLEGF', 'HW', 'MHVYF', 'MHVIY', 'WM', 'GD', 'ATLPF', 'ITOCF', 'ATLFF', 'TT', 'ATLKY', 'VRT', 'BAESF', 'ITOCY']
Raw path: /Users/rchbeir/Desktop/trading-bt/quant-github/projects/regime_adaptive_alpha/data/raw
Date range: 2016-01-01 to 2026-01-30

We use the Cell below to test the connection to all py files we have and if the configurations are loaded peoperly.  
### this is run to check that everything is connected

In [2]:
#testing the connection 
df = run_system_check()
df.head()

---- SETTINGS SUMMARY ----
Project name: regime_adaptive_alpha
Project root: /Users/rchbeir/Desktop/trading-bt/quant-github/projects/regime_adaptive_alpha
Raw path: /Users/rchbeir/Desktop/trading-bt/quant-github/projects/regime_adaptive_alpha/data/raw
Derived path: /Users/rchbeir/Desktop/trading-bt/quant-github/projects/regime_adaptive_alpha/data/derived
Features path: /Users/rchbeir/Desktop/trading-bt/quant-github/projects/regime_adaptive_alpha/data/features
Universe path: /Users/rchbeir/Desktop/trading-bt/quant-github/projects/regime_adaptive_alpha/data/universe
Reports path: /Users/rchbeir/Desktop/trading-bt/quant-github/projects/regime_adaptive_alpha/reports
Configured data window: 2016-01-01 to 2026-01-30
Adjustment: split
Feed: sip
Timezone: America/New_York
Base timeframe: 1Min
Derived timeframe: 5Min
Loaded tickers: 247
Testing symbol: NVDA

---- DATA CHECK ----
Pulled 1441 rows.
Columns: ['symbol', 'timestamp', 'open', 'high', 'low', 'close', 'volume', 'trade_count', 'vwap']

,symbol,timestamp,open,high,low,close,volume,trade_count,vwap
0,NVDA,2024-01-03 00:02:00+00:00,47.99,47.99,47.98,47.98,11580.0,43.0,47.98
1,NVDA,2024-01-03 00:03:00+00:00,47.98,47.98,47.98,47.98,4810.0,35.0,47.98
2,NVDA,2024-01-03 00:04:00+00:00,47.98,47.98,47.97,47.98,15260.0,51.0,47.98
3,NVDA,2024-01-03 00:05:00+00:00,47.98,47.98,47.96,47.96,4730.0,30.0,47.97
4,NVDA,2024-01-03 00:06:00+00:00,47.97,47.97,47.95,47.95,15410.0,48.0,47.96

Great! if no errors were seen above, it means that everything is connected succesfully and all the functions below are ready to use. but first we start by testing our backfill function. The backfill function takes in input of start year, end year and symbols and it fetches the data from alpaca and stores it in parquets in our data/raw/\<symbol>/\<symbol>_\<year>.parquet. we test it in the next cell

In [3]:
run_backfill(symbols=["AAPL"], start_year=2024, end_year=2024)

Skipping AAPL 2024 (already exists)

If the cell ran and you daw saved, it means that the data was saved in the proper file, now we test load_parquet to make sure we see it in our folders before we pull the 200 symbols we want.

In [4]:
df_aapl = load_parquet("AAPL", 2024, DATA_DIR)
df_aapl.head()

,symbol,timestamp,open,high,low,close,volume,trade_count,vwap
0,AAPL,2024-01-02 09:00:00+00:00,191.52,191.52,190.00,190.20,18933.0,612.0,190.241493
1,AAPL,2024-01-02 09:01:00+00:00,190.11,190.13,190.00,190.00,8562.0,425.0,190.088775
2,AAPL,2024-01-02 09:02:00+00:00,189.90,189.90,189.82,189.82,5355.0,129.0,189.823988
3,AAPL,2024-01-02 09:03:00+00:00,189.87,189.87,189.80,189.87,4405.0,83.0,189.859107
4,AAPL,2024-01-02 09:04:00+00:00,189.90,189.95,189.90,189.90,2225.0,87.0,189.916633

Great! now we can import all symbols, we have the symbols stored in configs/universe.yaml. we run the next cell to do so.
# This will download all the files

In [5]:
run_full_backfill()

You are about to run a full-universe backfill.
Number of tickers: 247
Years: 2016 to 2026
Total symbol-year jobs: 2717
Overwrite existing files: False

Type 'yes' to continue:  yes

Backfilling symbols:   0%|                          | 0/247 [00:00<?, ?symbol/s]

Skipping NVDA 2016 (already exists)
Skipping NVDA 2017 (already exists)
Skipping NVDA 2018 (already exists)
Skipping NVDA 2019 (already exists)
Skipping NVDA 2020 (already exists)
Skipping NVDA 2021 (already exists)
Skipping NVDA 2022 (already exists)
Skipping NVDA 2023 (already exists)
Skipping NVDA 2024 (already exists)
Skipping NVDA 2025 (already exists)
Fetching NVDA 2026 from 2026-01-01 00:00:00 to 2026-03-08 00:00:00...

Backfilling symbols:   0%|                  | 1/247 [00:02<10:28,  2.56s/symbol]

Saved NVDA 2026 to /Users/rchbeir/Desktop/trading-bt/quant-github/projects/regime_adaptive_alpha/data/raw/NVDA/NVDA_2026.parquet
Skipping AAPL 2016 (already exists)
Skipping AAPL 2017 (already exists)
Skipping AAPL 2018 (already exists)
Skipping AAPL 2019 (already exists)
Skipping AAPL 2020 (already exists)
Skipping AAPL 2021 (already exists)
Skipping AAPL 2022 (already exists)
Skipping AAPL 2023 (already exists)
Skipping AAPL 2024 (already exists)
Skipping AAPL 2025 (already exists)
Fetching AAPL 2026 from 2026-01-01 00:00:00 to 2026-03-08 00:00:00...

Backfilling symbols:   1%|▏                 | 2/247 [00:04<08:16,  2.03s/symbol]

Saved AAPL 2026 to /Users/rchbeir/Desktop/trading-bt/quant-github/projects/regime_adaptive_alpha/data/raw/AAPL/AAPL_2026.parquet
Skipping GOOG 2016 (already exists)
Skipping GOOG 2017 (already exists)
Skipping GOOG 2018 (already exists)
Skipping GOOG 2019 (already exists)
Skipping GOOG 2020 (already exists)
Skipping GOOG 2021 (already exists)
Skipping GOOG 2022 (already exists)
Skipping GOOG 2023 (already exists)
Skipping GOOG 2024 (already exists)
Skipping GOOG 2025 (already exists)
Fetching GOOG 2026 from 2026-01-01 00:00:00 to 2026-03-08 00:00:00...

Backfilling symbols:   1%|▏                 | 3/247 [00:06<08:42,  2.14s/symbol]

Saved GOOG 2026 to /Users/rchbeir/Desktop/trading-bt/quant-github/projects/regime_adaptive_alpha/data/raw/GOOG/GOOG_2026.parquet
Skipping MSFT 2016 (already exists)
Skipping MSFT 2017 (already exists)
Skipping MSFT 2018 (already exists)
Skipping MSFT 2019 (already exists)
Skipping MSFT 2020 (already exists)
Skipping MSFT 2021 (already exists)
Skipping MSFT 2022 (already exists)
Skipping MSFT 2023 (already exists)
Skipping MSFT 2024 (already exists)
Skipping MSFT 2025 (already exists)
Fetching MSFT 2026 from 2026-01-01 00:00:00 to 2026-03-08 00:00:00...

Backfilling symbols:   2%|▎                 | 4/247 [00:09<09:28,  2.34s/symbol]

Saved MSFT 2026 to /Users/rchbeir/Desktop/trading-bt/quant-github/projects/regime_adaptive_alpha/data/raw/MSFT/MSFT_2026.parquet
Skipping AMZN 2016 (already exists)
Skipping AMZN 2017 (already exists)
Skipping AMZN 2018 (already exists)
Skipping AMZN 2019 (already exists)
Skipping AMZN 2020 (already exists)
Skipping AMZN 2021 (already exists)
Skipping AMZN 2022 (already exists)
Skipping AMZN 2023 (already exists)
Skipping AMZN 2024 (already exists)
Skipping AMZN 2025 (already exists)
Fetching AMZN 2026 from 2026-01-01 00:00:00 to 2026-03-08 00:00:00...

Backfilling symbols:   2%|▎                 | 5/247 [00:12<10:16,  2.55s/symbol]

Saved AMZN 2026 to /Users/rchbeir/Desktop/trading-bt/quant-github/projects/regime_adaptive_alpha/data/raw/AMZN/AMZN_2026.parquet
Skipping TSM 2016 (already exists)
Skipping TSM 2017 (already exists)
Skipping TSM 2018 (already exists)
Skipping TSM 2019 (already exists)
Skipping TSM 2020 (already exists)
Skipping TSM 2021 (already exists)
Skipping TSM 2022 (already exists)
Skipping TSM 2023 (already exists)
Skipping TSM 2024 (already exists)
Skipping TSM 2025 (already exists)
Fetching TSM 2026 from 2026-01-01 00:00:00 to 2026-03-08 00:00:00...

Backfilling symbols:   2%|▎                 | 5/247 [00:14<11:43,  2.91s/symbol]

KeyboardInterrupt: